name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🎉 Added'
    labels:
      - 'enhancement'
      - 'feature'
  - title: '🔄 Changed'
    labels:
      - 'change'
      - 'refactor'
  - title: '🐛 Fixed'
    labels:
      - 'bug'
      - 'bugfix'
      - 'fix'
  - title: '📚 Documentation'
    labels:
      - 'documentation'
      - 'docs'
  - title: '🧪 Testing'
    labels:
      - 'test'
      - 'testing'
change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'minor'
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'patch'
      - 'bug'
      - 'bugfix'
      - 'fix'
  default: patch
template: |
  ## What's Changed
  
  $CHANGES
  
  **Full Changelog**: https://github.com/aa-parky/tonika_bus/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION