# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

sphinx:
  configuration: docs/conf.py

python:
  install:
    # Install the project itself so autodoc can import it
    - method: pip
      path: .
    # Install docs-specific requirements (MyST Markdown, RTD theme, etc.)
    - requirements: docs/requirements.txt
