name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: Test Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"

    - name: Run linting with ruff
      run: |
        ruff check src/ tests/

    - name: Run type checking with mypy
      run: |
        mypy src/tonika_bus/core/ --ignore-missing-imports
      continue-on-error: true  # Don't fail build yet, but show warnings

    - name: Run tests with pytest
      run: |
        pytest --cov=tonika_bus --cov-report=xml --cov-report=term-missing -v

    - name: Upload coverage to Coveralls
      if: matrix.python-version == '3.12'  # Only upload once
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        file: coverage.xml

  security:
    name: Security scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bandit[toml]

    - name: Run security scan with bandit
      run: |
        bandit -r src/ -ll
